openapi: 3.0.0
info:
  title: HMIS Export Service
  version: 1.0.1
servers:
  - url: 'https://www.hslynk.com/hmis-export-service/rest'
paths:
  /exports:
    post:
      responses:
        '200':
          description: OK – Everything is working.
          content:
            application/json:
              schema:
                example:
                  exportConfig:
                      name: 'First Name'
                      exportLevel: 'PROJECT'
                      exportType: 'HMIS'
                      id: 'uuid'
                      startDate: '01/01/2018'
                      endDate: '01/01/2019'
                      status: 'COMPLETED'
                      projectIds:
                        projectId : abc

      description:
       It creates request a export belonging to a project group by providing
        1) Name
        2) exportLevel
        3) exportType
        4) startDate
        5) endDate
        6) projectIds
        The user must have permission to use this API
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                exportLevel:
                  type: string
                exportType:
                  type: string
                startDate:
                  type: date
                endDate:
                  type: date
                projectId:
                  type: string
              example:
                  exportConfig:
                      name: 'First Name'
                      exportLevel: 'PROJECT'
                      exportType: 'HMIS'
                      startDate: '01/01/2018'
                      endDate: '01/01/2019'
                      projectIds:
                        projectId : abc
      operationId: POST_exports
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
    get:
      responses:
        '200':
          description: OK – Everything is working.
          content:
            application/json:
              schema:
                example:
                  exportConfigs:
                    pagination:
                      from: 0
                      returned: 3
                      total: 30
                      maximum: 30
                      sort: {}
                    exportConfigs:
                      - id: e7f87b3b-9282-4031-af3f-34bebc2c6cbf
                        name: 'First Name'
                        exportLevel: 'PROJECT'
                        exportType: 'HMIS'
                        emailSent: true
                        dateCreated:  '01/01/2019'
                        dateUpdasted: '01/01/2019'
                        startDate: '01/01/2018'
                        endDate: '01/01/2019'
                        status: 'COMPLETED'
      description: To get all the exports under logged in your project group.
      operationId: GET_exports
      parameters:
        - name: Authorization
          in: header
          required: true
          description: >-
            Authorization request header should specify as HMISUserAuth
            session_token={sessiontokenvalue}.
          schema:
            type: string
        - name: X-HMIS-TrustedApp-Id
          in: header
          required: true
          description: Trusted App id should be provide in this header.
          schema:
            type: string
        - name: startIndex
          in: query
          schema:
            default: '0'
            type: string
        - name: maxItems
          in: query
          schema:
            default: '30'
            type: string
  '/exports/{exportid}':
      put:
        responses:
          '200':
            description: OK – Everything is working.
            content:
              application/json:
                schema:
                  example:
                    exportConfig:
                      name: 'First Name'
                      id: 'exportid'
                      exportLevel: 'PROJECT'
                      exportType: 'HMIS'
                      startDate: '01/01/2018'
                      endDate: '01/01/2019'
                      status: 'COMPLETED'
                      projectIds:
                        projectId : abc
        description:
         Update a export by id.

          Provide export id as path variable for upatading non loggedin user. If
          need to update logged in user send self as export id.
          You can only update name,startDate,endDate,exportType and exportLevel.
        requestBody:
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: int
                  name:
                    type: string
                  exportLevel:
                    type: string
                  exportType:
                    type: string
                  startDate:
                    type: date
                  endDate:
                    type: date
                  projectId:
                    type: string
                example:
                    exportConfig:
                        name: 'First Name'
                        id: 'exportid'
                        exportLevel: 'PROJECT'
                        exportType: 'HMIS'
                        startDate: '01/05/2018'
                        endDate: '01/01/2019'
                        projectIds:
                          projectId : abc
        operationId: PUT_exports-exportid
      get:
        responses:
          '200':
            description: OK – Everything is working.
            content:
              application/json:
                schema:
                  example:
                    exportConfig:
                      name: 'First Name'
                      id: 'exportid'
                      exportLevel: 'PROJECT'
                      exportType: 'HMIS'
                      projectGroupCode: 'PRGCODE'
                      emailSent : true
                      dateCreated  : '01/01/2019'
                      dateUpdated : '01/01/2019'
                      startDate: '01/01/2018'
                      endDate: '01/01/2019'
                      status: 'COMPLETED'
                      projectIds:
                        projectId : abc
          '403':
            description: 'No export config found with this id'
            content:
              application/json:
                schema:
                  type: object
        description: |
          Gets (aka reads or retrieves) a specific account. <BR><br>
          GET /accounts/{username}
          <b>
        operationId: GET_exports-exportid
        parameters:
          - name: Authorization
            in: header
            required: true
            description: >-
              Authorization request header should specify as HMISUserAuth
              session_token={sessiontokenvalue}.
            schema:
              type: string
          - name: X-HMIS-TrustedApp-Id
            in: header
            required: true
            description: Trusted App id should be provide in this header.
            schema:
              type: string
      parameters:
      - name: exportid
        in: path
        required: true
        schema:
          type: int
  '/download/{exportid}/{type}':
      get:
        responses:
          '200':
            description: OK – Everything is working.
            content:
              application/force-download:
        description:
         Downloads a .pdf or .zip(sage csv zip) version of the HMIS export by providing the exportid and type.
         Type can either pdf or zip.
        operationId: GET_download_export-exportid
        parameters:
          - name: Authorization
            in: header
            required: true
            description: >-
              Authorization request header should specify as HMISUserAuth
              session_token={sessiontokenvalue}.
            schema:
              type: string
          - name: X-HMIS-TrustedApp-Id
            in: header
            required: true
            description: Trusted App id should be provide in this header.
            schema:
              type: string
      parameters:
      - name: exportid
        in: path
        required: true
        schema:
          type: int
      - name: type
        in: path
        required: true
        schema:
          type: string
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    oauth_2_0:
      description: |
        The HMIS API supports OAuth 2.0 for authenticating all API requests.
      type: oauth2
      flows:
        password:
          tokenUrl: 'https://hmislynk.com/hmis-authorization-service/rest/token'
          scopes:
            user: ''
            administrator: ''
  links: {}
  callbacks: {}
